### ISSUE TITLE
node.dll not exists

### ISSUE THREAD

**Issue by hepingchen** [E024/MiniBlinkPinvokeDemo#2]
node.dll not exists ,i can find it

**Comment by E024** [comment]
最新的node.dll可到官方QQ群 94093808 下载 或 https://github.com/weolar/miniblink49/releases 下载编译。最新官方API文档地址：https://weolar.github.io/miniblink/doc-main.html

**Comment by ghost** [comment]
[https://github.com/weolar/miniblink49/releases](https://github.com/weolar/miniblink49/releases)

我已经从这儿下载了node.dll，应该添加到项目何处？

![image](https://user-images.githubusercontent.com/36882078/44316701-8b41e500-a45f-11e8-9bbd-4f94848e5f8e.png)

**Comment by E024** [comment]
不需要引用，放到软件运行根目录即可。
