### ISSUE TITLE
使用MiniBlink 2018-8-10版Demo中的开发者工具不能使用.

### ISSUE THREAD

**Issue by cn-troy** [E024/MiniBlinkPinvokeDemo#3]
front_end文件夹是直接复制Miniblink2018-8-10版中的文件...
调试时发现代码
blinkBrowser1.ShowDevtools(Application.StartupPath + @"\front_end\inspector.html");
正常执行...但是打开的开发者工具是空白的...
请作者解答..谢谢..

**Comment by E024** [comment]
ShowDevtools 实验性接口，建议用 wkeSetDebugConfig 实现。
