### ISSUE TITLE
获取渲染后的Html文本的方法

### ISSUE THREAD

**Issue by huoxuxu** [E024/MiniBlinkPinvokeDemo#4]
请问：
  有没有获取渲染后的Html文本的方法呢？
Demo里没找到。。

**Comment by E024** [comment]
可通过 blinkBrowser1.HTML 获取（参照 https://github.com/E024/MiniBlinkPinvoke/blob/73539c36866057e9de106c9a9e20f3e05376bb65/MiniBlink/BlinkBrowser.cs#L1138 ），官方暂时没发现直接接口。

**Comment by huoxuxu** [comment]
大佬牛逼
