### ISSUE TITLE
怎么加载页面资源（html,css,js）

### ISSUE THREAD

**Issue by pjpv** [E024/MiniBlinkPinvokeDemo#6]
你好，demo使用的是单html文件，如果需要使用多个资源（html，js，css，图片)。
这些资源怎么怎么嵌入到程序里面？
![资源示例](https://i.loli.net/2019/04/28/5cc582a50bd3d.png)

**Comment by E024** [comment]
嵌入资源有多种，比如将资源以内嵌资源的方式（项目属性，资源里），将文件放到项目，在资源上点击右键，选择属性，在生成操作里选择嵌入的资源（目前DEMO使用的方式）。
最后注意资源里的资源路径。

**Comment by E024** [comment]
其实通过任意方法，只要你想的到，能取到资源，然后在 OnwkeLoadUrlBeginCallback 回调里设置wkeNetSetData 数据就好了。注意设置 wkeNetSetMIMEType
