### ISSUE TITLE
本地html文件改为utf8编码为乱码，代码中也从默认改为utf8

### ISSUE THREAD

**Issue by lukejian** [E024/MiniBlinkPinvokeDemo#7]
MiniBlinkPinvoke.BlinkBrowser中的OnwkeLoadUrlBeginCallback()方法

**Comment by E024** [comment]
https://github.com/E024/MiniBlinkPinvoke 更新了，你再看一下。

**Comment by lukejian** [comment]
已经好了，谢谢！
